// lib/constants.js

export const KENYA_COUNTIES = [
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Uasin Gishu",
  "Kiambu",
  "Machakos",
  "Kajiado",
  "Kericho",
  "Nyeri",
  "Meru",
  "Kakamega",
  "Bungoma",
  "Busia",
  "Siaya",
  "Homa Bay",
  "Migori",
  "Kisii",
  "Nyamira",
  "Bomet",
  "Narok",
  "Laikipia",
  "Nyandarua",
  "Murang'a",
  "Kirinyaga",
  "Embu",
  "Tharaka-Nithi",
  "Kitui",
  "Makueni",
  "Garissa",
  "Wajir",
  "Mandera",
  "Marsabit",
  "Isiolo",
  "Samburu",
  "Turkana",
  "West Pokot",
  "Trans Nzoia",
  "Elgeyo-Marakwet",
  "Nandi",
  "Vihiga",
  "Tana River",
  "Lamu",
  "Taita-Taveta",
  "Kilifi",
  "Kwale",
];

export const NAIROBI_SHIPPING_FEE = 300;
export const DEFAULT_SHIPPING_FEE = 600;